---
name: "Release"
on:
  push:
    tags:
      - "v*"
jobs:
  goreleaser:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - name: "Import GPG key"
        id: "import_gpg"
        uses: "crazy-max/ghaction-import-gpg@v6"
        with:
          gpg_private_key: "${{ secrets.GPG_PRIVATE_KEY }}"
      - uses: "actions/setup-go@v5"
      - uses: "goreleaser/goreleaser-action@v6"
        with:
          args: "release --clean"
        env:
          GPG_FINGERPRINT: "${{ steps.import_gpg.outputs.fingerprint }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
